### ISSUE TITLE
Version bump

### ISSUE THREAD

**Issue by aashay** [yatish27/salesforce_bulk_api#31]
We could use another gem version bump.  Version 0.0.9 (current version on rubygems) does not include some important changes, such as getting rid of Rails calls:

https://github.com/yatish27/salesforce_bulk_api/commit/8132635d38354005af2bad6087d9d67a47e2c1cf#diff-c54fc188605097c5989b3994bd6b5c75L38

Thank you in advance!

**Comment by gostrc** [comment]
@yatish27 I believe this can now be closed because 0.0.11 was put on ruby gems and tagged in git
