### ISSUE TITLE
Bump bulk api

### ISSUE THREAD

**Issue by gostrc** [yatish27/salesforce_bulk_api#37]
I set the version to '32.0' in my own branch and it seems to work for the most part.

https://github.com/gostrc/salesforce_bulk_api/tree/bump-api

I did this because there are some fields that require this newer version bump.

e.g. I was getting this error before bumping the api:
```
ERROR at Row:1:Column:427 No such column 'CleanStatus' on entity 'Account'. If you are attempting to use a custom field, be sure to append the '__c' after the custom field name. Please reference your WSDL or the describe call for the appropriate names.
```

I didn't create a pull request in case you wanted to do some extra testing around the branch.
I noticed that null values came up with the following value:
```
"field"=>[{"xsi:nil"=>"true"}],
```

**Comment by yatish27** [comment]
Can you send a PR with latest master
