### ISSUE TITLE
@session_id is nil when using Restforce

### ISSUE THREAD

**Issue by demonmind** [yatish27/salesforce_bulk_api#53]
Hi,

when I user Restforce client with username and password + client_id and client_secret the @session_id is is nil. Instead if i use a token from Salesforce OAuth2 authentication with no username and password the @session_id is correctly set.

Is there any workaround for this?

**Comment by jeffdonthemic** [comment]
@demonmind, take a look at [this code](https://gist.github.com/jeffdonthemic/856328ffafa2cd705068). Should successfully return a sessionId for you.
