### ISSUE TITLE
is this gem still being maintained?

### ISSUE THREAD

**Issue by dzivalli** [yatish27/salesforce_bulk_api#69]
@yatish27 I see the last release being made on Jan 10, 2015 however master has some new commits with  bug fixes. Are you going to make a new release?

**Comment by yatish27** [comment]
Yes, I will release the updated version this weekend

**Comment by dzivalli** [comment]
cool, thanks!

**Comment by ignatbagaev** [comment]
hey @yatish27
seems like the version is still not updated at the rubygems. can you please release it?

**Comment by andyw8** [comment]
As this wasn't resolved, I created a new issue: #77
